export enum StatusTagEnum {
    ACTIVE = "active",
    INACTIVE = "inactive",
    PENDING = "pending",
    BLOCKED = "blocked",
    DELETED = "deleted",
    EXPIRED = "expired",
    CUSTOM = "custom",
    COMPLETED = "completed",
    INPROGRESS = "inprogress",
    FAILED = "failed",
    SUCCESS = "success",
    NO_STATUS = "-",
    TERMINATED = "terminated",
    PROCESSING = "processing",
    CLOSED = "closed",
    SUSPENDED = "suspended",
    DRAFT = "draft",
    BARRED = "barred",
    NO_RECORDS = "no_records"
}