export enum ConfigNamesEnumModel {
    OTPLength = "OTPLength",
    OTPValidity = "OTPValidity",
    OTPRetryCount = "OTPRetryCount",
    OTPValidityList = "OTPValidityList",
    OTPLengthList = "OTPLengthList",
    OTPRetryCountList = "OTPRetryCountList",
    MinRechargeValue = "MinRechargeValue",
    MaxRechargeValue = "MaxRechargeValue",
    MsisdnValidationRegex = "MsisdnValidationRegex",
    BalanceTransferPINLength = "BalanceTransferPINLength",
    IdNumberMaxLength = "IdNumberMaxLength",
    RefreshTokenRequestTimeRangeInSeconds = "RefreshTokenRequestTimeRangeInSeconds",
    Version = "Version",
}