# Use official node image as the base image
#FROM 10.200.140.150:5000/node-build-react:LANGUAGE_VERSION as build
#FROM node:22-bullseye as build
FROM 10.200.140.150:5000/node-build-react:18 as build

# Stage 0: Compile and Build angular codebase

# Set the working directory
RUN mkdir /app

WORKDIR /app

# copy package.json to app directory
#COPY . /app
COPY package.json /app
COPY /envfiles/.env.dev /app
#COPY ./envfiles/.env.staging /app

RUN ls -la /app/*
# Install all the dependencies
RUN npm install

#copy code to app directory
COPY . /app
RUN ls -la /app/*

# Install all the dependencies

RUN npm run build:development

RUN ls -la /app/*

RUN ls -la /app/dist
# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

#ENV TZ=Africa/Gaborone
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN rm -f /etc/nginx/conf.d/default.conf
COPY mascom.conf /etc/nginx/conf.d/
#RUN sed -i '10i try_files $uri /index.html;' /etc/nginx/conf.d/default.conf

# Copy the build output to replace the default nginx contents.
COPY --from=build /app/dist /usr/share/nginx/html/dist
#COPY --from=build /app/default.conf /etc/nginx/conf.d/

RUN cd /usr/share/nginx && ls

RUN chmod -R 775 /usr/share/nginx/html/*
